name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  image: mysql:8.0.26
  MYSQL_DATABASE: base
  MYSQL_USER: root
  MYSQL_PASSWORD: root
#  MYSQL_ROOT_PASSWORD: rootpassword

#  POSTGRESQL_VERSION: 13.1
#  POSTGRESQL_DB: base
#  POSTGRESQL_USER: postgres
#  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 1.16

jobs:
  build:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: mysql:8.0.26
#        env:
#          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
#          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
#          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql.service -P 3301
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean install
